### ISSUE TITLE
upload to 1.20.6 please?

### ISSUE THREAD

**Issue by drkhodakarami** [tratt-mods/LiterallyChunkLoader#23]
With changes happening about network in Minecraft 1.20.6, will you please update the mod to this version?

**Comment by tratteo** [comment]
Hi @drkhodakarami, **1.20.6 Fabric** is available [here](https://www.curseforge.com/minecraft/mc-mods/literally-chunk-loader/files/5366736).
 
Cheers 🙋!

**Comment by drkhodakarami** [comment]
Thanks
